engineering/calc_app/urls.py
from django.urls import path
from . import views

app_name = 'calc_app'

urlpatterns = [
    path('section_prop/', views.rectangle, name='rectangle'),
    path('fan_unbalance/', views.fan_unbalance, name="fan_unbalance"),
    path('earthquake_load/', views.earth_quake, name="earth_quake"),
]

engineering/engineering/urls.py
from django.contrib import admin
from django.urls import path, include
from calc_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('calc_app/', include('calc_app.urls')),

]

engineering/calc_app/models.py
from django.db import models
import datetime
from django import forms

# Create your models here.


class Rectangle(models.Model):
    rec_width = models.DecimalField(max_digits=10, decimal_places=2)
    rec_height = models.DecimalField(max_digits=10, decimal_places=2)
    date_recorded = models.DateField(auto_now=True)


class FanUnbalance(models.Model):
    BALANCE_CHOICE = ['1', '2.5', '6.3']
    balance_grade = models.CharField(max_length=10, choices=[(x, x) for x in BALANCE_CHOICE], default='2.5')
    impeller_mass = models.DecimalField(max_digits=10, decimal_places=2)
    fan_speed = models.DecimalField(max_digits=10, decimal_places=2)
    backplate_dia = models.DecimalField(max_digits=10, decimal_places=2)

class EarthQuake(models.Model):
    SITECLASS_CHOICES = ['A', 'B', 'C', 'D', 'E']
    RISK_CHOICES = ['1', '2', '3', '4']
    STRUCT_TYPE_CHOICES = ("Steel moment-resisting frames", "Concrete moment-resisting frames", "Steel eccentrically braced frames in accordance with Table 12.2-1 lines B1 or D1", "Steel buckling-restrained braced frames", "All other structural systems")
    site_class = models.CharField(max_length=1, choices=[(x, x) for x in SITECLASS_CHOICES], default='D')
    res_mod_coeff= models.DecimalField('R Value', max_digits=6, decimal_places=5, default=3)
    risk_cat = models.CharField('Risk Category', max_length=100, choices=[(x, x) for x in RISK_CHOICES], default='2')
    s1= models.DecimalField('S1', max_digits=6, decimal_places=5)
    ss= models.DecimalField('Ss', max_digits=6, decimal_places=5)
    fund_period = models.DecimalField('T', max_digits=6, decimal_places=3)
    long_period = models.DecimalField('TL', max_digits=6, decimal_places=3)
    height = models.DecimalField('Height', max_digits=6, decimal_places=3)
    structure_type = models.CharField('Structure Type', max_length=100, choices=[(x, x) for x in STRUCT_TYPE_CHOICES], default= "All other structural systems")
    site_class_calculated = models.BooleanField(default=False)

engineering/calc_app/forms.py
from django import forms
from .models import Rectangle, FanUnbalance, EarthQuake


class RectangleForm(forms.ModelForm):
    class Meta():
        model = Rectangle
        fields = '__all__'


class FanUnbalanceForm(forms.ModelForm):
    class Meta():
        model = FanUnbalance
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['balance_grade'].widget.attrs.update({'class': 'special'})
        self.fields['impeller_mass'].widget.attrs.update({'class': 'special'}, size='200')


class EarthQuakeForm(forms.ModelForm):
    class Meta():
        model = EarthQuake
        fields = '__all__'

            #   <!-- <div class="col-6">
            #      {{ form.site_class|as_crispy_field }}
            #   </div> -->
            #   <!-- <div class="col-6">
            #       {{ form.res_mod_coeff|as_crispy_field }}
            #    </div> -->
            #    <!-- <div class="col-6">
            #       {{ form.risk_cat|as_crispy_field }}
            #    </div> -->
            #    <!-- <div class="col-6">
            #       {{ form.s1|as_crispy_field }}
            #    </div> -->
            #    <!-- <div class="col-6">
            #       {{ form.ss|as_crispy_field }}
            #    </div> -->
            #    <!-- <div class="col-6">
            #       {{ form.fund_period|as_crispy_field }}
            #    </div> -->
            #    <!-- <div class="col-6">
            #       {{ form.long_period|as_crispy_field }}
            #    </div> -->

engineering/calc_app/views.py
from django.shortcuts import render
from calc_app.forms import RectangleForm, FanUnbalanceForm, EarthQuakeForm
from lib.rectangle_properties import Rect
from lib.fan_unbalance import Fan
from lib.earthquake_load import Quake
from . models import Rectangle, FanUnbalance, EarthQuake

# Create your views here.


def index(request):
    return render(request, 'index.html')


def rectangle(request):

    form = RectangleForm()

    if request.method == 'POST':
        form = RectangleForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            x = float(form.cleaned_data['rec_width'])
            y = float(form.cleaned_data['rec_height'])

            arta = Rect(x, y)
            result1 = arta.area()
            result2 = round(arta.p_moment(), 2)
            result3 = "Area = "
            result4 = "Principal Moment of Inertia = "

            return render(request, 'section_prop.html', {'form': form, 'result1': result1, 'result2': result2, 'result3': result3, 'result4': result4})
        else:
            print('Form Invalid')

    return render(request, 'section_prop.html', {'form': form})


def fan_unbalance(request):
    form = FanUnbalanceForm()

    if request.method == 'POST':
        form = FanUnbalanceForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            A = float(form.cleaned_data['balance_grade'])
            B = float(form.cleaned_data['impeller_mass'])
            C = float(form.cleaned_data['fan_speed'])
            D = float(form.cleaned_data['backplate_dia'])

            fan = Fan(A, B, C, D)
            result1 = fan.pru()
            result2 = fan.patch_area()
            result3 = "Premissable Residual Unbalance = "
            result4 = "Max. Patch Area = "

            return render(request, 'fan_unbalance.html', {'form': form, 'result1': result1, 'result2': result2, 'result3': result3, 'result4': result4})
        else:
            print('Form Invalid')

    return render(request, 'fan_unbalance.html', {'form': form})

def earth_quake(request):
    form = EarthQuakeForm()

    if request.method == 'POST':
        form = EarthQuakeForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            A = form.cleaned_data['site_class']
            B = float(form.cleaned_data['res_mod_coeff'])
            C = int(form.cleaned_data['risk_cat'])
            D = float(form.cleaned_data['ss'])
            E = float(form.cleaned_data['s1'])
            F = float(form.cleaned_data['fund_period'])
            G = float(form.cleaned_data['long_period'])
            H = float(form.cleaned_data['height'])
            I = form.cleaned_data['structure_type']
            J = form.cleaned_data['site_class_calculated']
            

            quake = Quake(A, B, C, D, E, F, G, H, I, J)
            result1 = quake.importance_factor()
            result2 = quake.fa()
            result3 = quake.fv()
            result4 = quake.sm_one()
            result5 = quake.sm_s()
            result6 = quake.sd_one()
            result7 = quake.sd_s()
            result8 = quake.cs()
            result9 = quake.cu()
            result10 = quake.ct()
            result11 = quake.x()
            result12 = quake.seismic_design_cat()
            result13 = quake.fv_warning()
            result14 = quake.ta()
            



            return render(request, 'earthquake_load.html', {'form': form, 'result1': result1, 'result2': result2, 'result3': result3,
             'result4': result4, 'result5': result5, 'result6': result6,
              'result7': result7, 'result8': result8, 'result9': result9,
              'result10': result10, 'result11': result11, 'result12': result12, 'result13': result13, 'result14': result14})
            # return render(request, 'earthquake_load.html', {'form': form,'result8': result8})
        else:
            print('Form Invalid')

    return render(request, 'earthquake_load.html', {'form': form})


# def wind(request):

engineering/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">


          <li><a class="navbar-brand" href="{% url 'index' %}">HOME</a></li>
          <li><a class="navbar-link" href="{% url 'calc_app:rectangle' %}">Rectangle</a></li>
          <li><a class="navbar-link" href="{% url 'calc_app:fan_unbalance' %}">Fan Unbalance</a></li>
          <li><a class="navbar-link" href="{% url 'calc_app:earth_quake' %}">EarthQuake Load</a></li>



        </ul>
      </div>
    </nav>

            {% block body_block %}
            {% endblock %}

    </body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>

engineering/templates/earthquake_load.html
{% extends "base.html" %}
 {% load crispy_forms_tags %} 
{% block body_block %}
<div class="container">
        <div class="row justify-content-center">
          <div class="col-8">
            <h2 class="mt-2">Fan Unpalance Calculator</h2>
            <hr class="mt-0 mb-4">
            </div>
        </div>
      </div>
     <div class="container">
        <div class="jumbotron"> 

    <h1>FAN UNBALANCE</h1>
   <form class="form-group row" method="POST">
    <div class="col-sm-10"> 
    <div class="container">
        <div class="jumbotron">
      <form method="POST" novalidate>
          <div class="row">
                <div class="col-6">
                 {{ form.site_class|as_crispy_field }}
                </div> 
                <div class="col-6">
                  {{ form.res_mod_coeff|as_crispy_field }}
                </div> 
                <div class="col-6">
                  {{ form.risk_cat|as_crispy_field }}
                </div> 
                 
                <div class="col-6">
                  {{ form.ss|as_crispy_field }}
               </div> 
               <div class="col-6">
                    {{ form.s1|as_crispy_field }}
                 </div>
                <div class="col-6">
                  {{ form.fund_period|as_crispy_field }}
               </div>
               <div class="col-6">
                  {{ form.long_period|as_crispy_field }}
               </div>  
               <div class="col-6">
                  {{ form.height|as_crispy_field }}
               </div>  
               <div class="col-6">
                  {{ form.structure_type|as_crispy_field }}
               </div>  
               <div class="col-6">
                  {{ form.site_class_calculated|as_crispy_field }}
               </div>  
               
        {% csrf_token %}
               <hr>
            <div class="col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div> 

   </form>

</div>
</div>
</div>

<div>
<p></p>
<p></p>
<hr>
<h3>Seismic Response Coefficient Cs = <span style="color:blue">{{ result8 }}</span></h3>

<hr>
<h4> Importance Factor = <span style="color:blue">{{ result1 }}</span></h4>
<h4> Fa = <span style="color:blue">{{ result2 }}</span></h4>
<h4> Fv = <span style="color:blue">{{ result3 }} {{ result13}}</span></h4>
<h4> Sm1 = <span style="color:blue">{{ result4 }}</span></h4>
<h4> Sms = <span style="color:blue">{{ result5 }}</span></h4>
<h4> SD1 = <span style="color:blue">{{ result6 }}</span></h4>
<h4> SDs = <span style="color:blue">{{ result7 }}</span></h4>
<h4>  Period upper limit coefficient = <span style="color:blue">{{ result9 }}</span></h4>
<h4>  Ct parameter = <span style="color:blue">{{ result10 }}</span></h4>
<h4>  x parameter = <span style="color:blue">{{ result11 }}</span></h4>
<h4>  Ta = <span style="color:blue">{{ result14 }}</span></h4>
<h4>  Seismic design category = <span style="color:blue">{{ result12 }}</span></h4>
<p></p>
 
</div>
{% endblock %}


quake = Quake(A, B, C, D, E, F, G, H, I, J)
result1 = quake.importance_factor()
result2 = quake.fa()
result3 = quake.fv()
result4 = quake.sm_one()
result5 = quake.sm_s()
result6 = quake.sd_one()
result7 = quake.sd_s()
result8 = quake.cs()
result9 = quake.cu()
result10 = quake.x()
result11 = quake.ta()
result12 = quake.seismic_design_cat()

engineering/templates/fan_unbalance.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block body_block %}
<div class="container">
        <div class="row justify-content-center">
          <div class="col-8">
            <h2 class="mt-2">Fan Unpalance Calculator</h2>
            <hr class="mt-0 mb-4">
            </div>
        </div>
      </div>
    <!-- <div class="container">
        <div class="jumbotron"> -->

   <!-- <h1>FAN UNBALANCE</h1>
   <form class="form-group row" method="POST">
    <div class="col-sm-10"> -->
    <div class="container">
        <div class="jumbotron">
      <form method="POST" novalidate>
          <div class="row">
              <div class="col-6">
                 {{ form.balance_grade|as_crispy_field }}
              </div>
              <div class="col-6">
                  {{ form.impeller_mass|as_crispy_field }}
               </div>
               <div class="col-6">
                  {{ form.fan_speed|as_crispy_field }}
               </div>
               <div class="col-6">
                  {{ form.backplate_dia|as_crispy_field }}
               </div>
        {% csrf_token %}
      <div class="col-sm-10">
          <button type="submit" class="btn btn-success">Submit</button>      <!-- </div>
    </div> -->

   </form>

</div>
</div>
</div>

<div>
<p></p>
<p></p>
<hr>
<h4>{{ result3}}<span style="color:blue">{{ result1 }}</span></h4>
<p></p>
<hr>
<h4>{{ result4 }}<span style="color:blue">               {{ result2 }}</span></h4>
</div>
{% endblock %}

engineering/templates/index.html
{% extends "base.html" %}
{% block body_block %}
<div class="container">
        <div class="row justify-content-center">
          <div class="col-8">
            <h1 class="mt-2">Calculator</h1>
            <hr class="mt-0 mb-4">
            </div>
        </div>
      </div>
<div class="container">
        <div class="jumbotron">
   <h2>Please selece calculation page</h2>

   <a href="calc_app/section_prop">Section Properties</a>
   <br>
   <a href="calc_app/fan_unbalance">Fan Unbalance</a>

</div>
</div>
   {% endblock %}

engineering/templates/section_prop.html
{% extends "base.html" %}

{% block body_block %}
<div class="container">
        <div class="row justify-content-center">
          <div class="col-8">
            <h2 class="mt-2">Rectangular Section Properties Calculator</h2>
            <hr class="mt-0 mb-4">
            </div>
        </div>
      </div>
    <div class="container">
        <div class="jumbotron">
      <form method="POST">
        {{ form.as_p}}
        {% csrf_token %}
        <button type="submit" class="btn btn-success">Submit</button>

   </form>

</div>
<p></p>
<p></p>
<hr>
<h4>{{result3}}   <span style="color:blue">{{ result1 }} </span> </h4>
<p></p>
<hr>
<h4>{{result4}}<span style="color:blue">{{ result2 }} </span> </h4>
</div>
{% endblock %}